### ISSUE TITLE
Any way to delay the decision of where gnat_util writes?

### ISSUE THREAD

**Issue by Ptival** [simonjwright/gnat_util#1]
Hi, I'm trying to build gnat_util on Nix, but I'm finding it difficult because it seems to want to write in subdirectories of its build directories. Nix builds are done in a sandbox and copied into a readonly store to avoid such mutation and have reproducible builds.

Is there any way to have these directories be configurable after the build and installation?

**Comment by simonjwright** [comment]
Normally, there'd be a source tree and a build tree; gnat\_util merges the two, but they could be separated if that's needed (so that gnat\_util could build "out-of-tree").

I find it hard to believe that Nix won't allow a build *tree* (i.e. a hierarchy of directories under the root build directory). GCC itself uses subdirectories of its build directory. Please explain.

**Comment by simonjwright** [comment]
> Is there any way to have these directories be configurable after the build and installation?

The build directories are `src`, `.build*`, `lib/**`.

**Comment by Ptival** [comment]
Nix allows the build tree while the package is being built, but it then freezes it after the package is installed, so that the package may not modify itself while it runs.

My problem is that when I run gprbuild, after gnat_util build and install are done, e.g. while building ASIS:
```
gprbuild -p  -XBLD=prod snames.gpr
```

It seems to be attempting to write into the readonly gnat_util build tree:

```
gprbuild: object directory "/nix/store/7nwn7kiyyf1bjf2cs8z18wv10cb669fg-gnat_util/share/gpr/.build-static/" for project "gnat_util" is not writable
```

Is this expected, or did I make a mistake in some configuration?

**Comment by Ptival** [comment]
One thing I am doing that may not be what I should do is to put `/nix/store/7nwn7kiyyf1bjf2cs8z18wv10cb669fg-gnat_util/share/gpr/` in my `GPR_PROJECT_PATH` so that gprbuild can find the `gnat_util.gpr` file there.

Should it instead go through `gnat_util.so` or something? Even when I try to put `/nix/store/7nwn7kiyyf1bjf2cs8z18wv10cb669fg-gnat_util/lib/` in my `LIBRARY_PATH`, without the one in `GPR_PROJECT_PATH`, I get this error:

```
gprbuild -p  -XBLD=prod -vl \
        tools/tool_utils/generate_factory.gpr

==============Messages for file: /build/source/common.gpr
    24. with "gnat_util";
             |
        >>> imported project file "gnat_util" not found
        >>> imported by "/build/source/common.gpr"
        >>> imported by "/build/source/asis.gpr"
        >>> imported by "/build/source/tools/tool_utils/generate_factory.gpr"
gprbuild: "tools/tool_utils/generate_factory.gpr" processing failed
```

Is it supposed to have access to `gnat_util.gpr`? And if so, how do I avoid the previous problems?

**Comment by simonjwright** [comment]
`make install` (or, if necessary, `sudo make install`) will, by default, install `gnat_util` with GNAT (line 74 of the Makefile). After that, `with "gnat_util";` should work without further ado - no need to specify `GPR_PROJECT_PATH`.

And the build tree is no longer needed.

If that’s not allowed, you can install wherever you like by
```
make install prefix=/where/ever
```
but you’d then have to specify
```
GPR_PROJECT_PATH=/where/ever/lib/gnat
```
(hmm, AdaCore’s packages install to `$prefix/share/gpr`, perhaps I should fall into line)

Or, you could write-protect all the `.ali` files in the build tree, stops GNAT recompiling them.

**Comment by Ptival** [comment]
Ok, I can't do the first solution because gnat's directory is also readonly.

The latter is pretty much what I was doing, except I did not realize I should use the `lib/gnat` suffix, thanks!
